name: maven.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven # Dòng này giúp tự động cache thư mục ~/.m2/repository

      # Chạy lệnh Maven verify (bao gồm cả test và check jacoco rule 80%)
      - name: Build and Test with Maven (JaCoCo check)
        run: mvn clean verify

      # Trích xuất và lưu trữ báo cáo JaCoCo sau khi build
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        if: always() # Chạy bước này ngay cả khi build fail (do coverage < 80%)
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/